version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: udyam_user
      POSTGRES_PASSWORD: udyam_pass
      POSTGRES_DB: udyam_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: